Script started on 2025-03-01 17:13:38-08:00
]0;janiceh6@crystalcove:hw4[janiceh6@crystalcove hw4]$ make
gcc -Wall -lm -std=c11 -c Advanced.c -o Advanced.o
gcc -Wall -std=c11 -c DIPs.c -o DIPS.o
gcc -Wall -std=c11 -c FileIO.c -o FileIO.o
gcc -Wall -std=c11 -c PhotoLab.c -o PhotoLab.o
gcc -Wall -std=c11 -c Test.c -o Test.o
gcc -Wall -std=c11 -c Image.c -o Image.o
gcc -Wall -lm -std=c11 PhotoLab.o DIPS.o Image.o Test.o Advanced.o FileIO.o -o PhotoLab
gcc -Wall -std=c11 -DDEBUG -o PhotoLabTest PhotoLab.c DIPs.c Advanced.c FileIO.c Image.o Test.o -lm
]0;janiceh6@crystalcove:hw4[janiceh6@crystalcove hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image horizontally
10: Add border to an image
11: Pixelate an image
12: Shift an image
13: Crop an image 
14: Resize an image
15: Add Watermark to an image
16: Rotate an image by 90 degree
17: Test all functions
18: Exit
Please make your choice: 17
0 mismatching pixels (0.000%) identified in bw_diff.ppm.
0 mismatching pixels (0.000%) identified in negative_diff.ppm.
0 mismatching pixels (0.000%) identified in colorfilter_diff.ppm.
0 mismatching pixels (0.000%) identified in edge_diff.ppm.
0 mismatching pixels (0.000%) identified in shuffle_diff.ppm.
0 mismatching pixels (0.000%) identified in vflip_diff.ppm.
0 mismatching pixels (0.000%) identified in hmirror_diff.ppm.
0 mismatching pixels (0.000%) identified in border_diff.ppm.
0 mismatching pixels (0.000%) identified in pixelate_diff.ppm.
0 mismatching pixels (0.000%) identified in shift_diff.ppm.
0 mismatching pixels (0.000%) identified in crop_diff.ppm.
0 mismatching pixels (0.000%) identified in smallresize_diff.ppm.
0 mismatching pixels (0.000%) identified in bigresize_diff.ppm.
0 mismatching pixels (0.000%) identified in watermark_diff.ppm.
0 mismatching pixels (0.000%) identified in rotateby90_diff.ppm.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image horizontally
10: Add border to an image
11: Pixelate an image
12: Shift an image
13: Crop an image 
14: Resize an image
15: Add Watermark to an image
16: Rotate an image by 90 degree
17: Test all functions
18: Exit
Please make your choice: 18
You exit the program.
]0;janiceh6@crystalcove:hw4[janiceh6@crystalcove hw4]$ valgrind --leak-check=full ./PhotoLabTest
==3541222== Memcheck, a memory error detector
==3541222== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==3541222== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==3541222== Command: ./PhotoLabTest
==3541222== 
EngPlaza.ppm was read successfully!
bw.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in bw_diff.ppm.
bw.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
negative.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in negative_diff.ppm.
negative.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
colorfilter.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in colorfilter_diff.ppm.
colorfilter.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
edge.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in edge_diff.ppm.
edge.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
shuffle.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in shuffle_diff.ppm.
shuffle.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
vflip.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in vflip_diff.ppm.
vflip.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
hmirror.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in hmirror_diff.ppm.
hmirror.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
border.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in border_diff.ppm.
border.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
pixelate.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in pixelate_diff.ppm.
pixelate.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
shift.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in shift_diff.ppm.
shift.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
crop.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in crop_diff.ppm.
crop.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
smallresize.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in smallresize_diff.ppm.
smallresize.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
bigresize.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in bigresize_diff.ppm.
bigresize.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
watermark_template.ppm was read successfully!
watermark.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in watermark_diff.ppm.
watermark.jpg was stored for viewing. 
EngPlaza.ppm was read successfully!
rotateby90.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in rotateby90_diff.ppm.
rotateby90.jpg was stored for viewing. 
==3541222== 
==3541222== HEAP SUMMARY:
==3541222==     in use at exit: 0 bytes in 0 blocks
==3541222==   total heap usage: 147 allocs, 147 frees, 9,068,240 bytes allocated
==3541222== 
==3541222== All heap blocks were freed -- no leaks are possible
==3541222== 
==3541222== For lists of detected and suppressed errors, rerun with: -s
==3541222== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;janiceh6@crystalcove:hw4[janiceh6@crystalcove hw4]$ make clean
rm -f *.o PhotoLab PhotoLabTest 
rm -f bigresize_diff.ppm negative.ppm vflip.ppm pixelate.ppm watermark_diff.ppm smallresize_diff.ppm edge_diff.ppm hmirror_diff.ppm shift_diff.ppm negative_diff.ppm bw.ppm bigresize.ppm rotateby90_diff.ppm colorfilter_diff.ppm smallresize.ppm bw_diff.ppm rotateby90.ppm crop_diff.ppm hmirror.ppm edge.ppm shuffle.ppm vflip_diff.ppm pixelate_diff.ppm border_diff.ppm colorfilter.ppm shift.ppm crop.ppm shuffle_diff.ppm watermark.ppm 
]0;janiceh6@crystalcove:hw4[janiceh6@crystalcove hw4]$ exit
exit

Script done on 2025-03-01 17:14:53-08:00
